### PR TITLE
Issue-18

### LINKED ISSUE #18: Broken Access Control - WP Email
The plugins ajax feature for reset, could be execute as a unauth

1. Do static analysis in line 176
help-scout\controllers\Settings.php
2. You will see ajax request "hsd_reset_customer_ids"
3. Since there are not nonce verified, we can make request like this

### PR DESCRIPTION
**Pull request by avonville**
Fixes #18

### CODE REVIEW

File: controllers/_Settings.php [hunk 1]
```diff
@@ -409,16 +378,17 @@ public static function setting_form_field( $name, $data ) {
...
-					'show_option_none' => __( '-- Select --', 'sprout-invoices' ),
+					'show_option_none' => __( '-- Select --', 'help-scout' ),
 					'option_none_value' => '0',
 					'selected' => $data['default'],
 					);
 				$parsed_args = wp_parse_args( $data['args'], $defaults );
-				wp_dropdown_pages( $parsed_args ); ?>
-		<?php elseif ( $data['type'] == 'bypass' ) : ?>
-			<?php if ( isset( $data['output'] ) ) { echo $data['output']; } // not escaped ?>
+				wp_dropdown_pages( $parsed_args ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (jamesros161) [inline controllers/_Settings.php]: If the whole point of this patch is to fix security issues, why are you ignoring this escaping?

**Review by jamesros161 — CHANGES_REQUESTED** [review]

**Review by jamesros161 — APPROVED** [review]
